### PR TITLE
Sticky Footer

### LINKED ISSUE #74: Sticky footer block
image

image

### PR DESCRIPTION
**Pull request by vivesing**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #74 

Test URLs:
- Before: https://main--icicidirect--aemsites.hlx.live/research/equity
- After: https://stickyfooter--icicidirect--aemsites.hlx.live/draft/vivesing/stickyfooter

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
Sticky Footer | https://stickyfooter--icicidirect--aemsites.hlx.live/sidekick/blocks/stickyfooter 

image

### CODE REVIEW

**Comment by ravverma** [comment]
image
spacing in mob view

**Comment by ravverma** [comment]
Can we do it without block creation as this doesn't need any specific layout ? 
Just `open and account link` in the section and style say `sticky-bottom` 
and for `open trading account link `and  `sticky-right` another section

**Review by ravverma — COMMENTED** [review]
added some comments

**Comment by vivesing** [comment]
> Can we do it without block creation as this doesn't need any specific layout ?
> Just open and account link in the section and style say sticky-bottom
> and for open trading account link and sticky-right another section

IIUC you recommend to include this as part of main section and add css classes in the style.css? 
I perfer creating a block because there are other styling that is specific to this section along with observers that are fired when scrolled after the block placement in the doc

**Comment by anagarwa** [comment]
@vivesing  small mobile view (320) might still need some spacing styling

image

**Comment by JiangLong2019** [comment]
A quick question, I tried to input a phone number and clicked the button on original site. Looks like it send a POST request with the number and did some validations. Shall we implement the same?

image

**Comment by vivesing** [comment]
> @vivesing small mobile view (320) might still need some spacing styling

@anagarwa it should be fixed now, there were some missing changes from the main

**Comment by vivesing** [comment]
> spacing in mob view

@ravverma thanks for pointing it out, fixed it.

**Comment by vivesing** [comment]
> A quick question, I tried to input a phone number and clicked the button on original site. Looks like it send a POST request with the number and did some validations. Shall we implement the same?

@JiangLong2019 Yes, I have skipped it intentionally and have opened a question for the customer to recommend the business rules and account creation flow once we click on the submit button. I have added the mobile number validation from their website and the rest can be added once they respond to that.

**Comment by ravverma** [comment]
> > Can we do it without block creation as this doesn't need any specific layout ?
> > Just open and account link in the section and style say sticky-bottom
> > and for open trading account link and sticky-right another section
> 
> IIUC you recommend to include this as part of main section and add css classes in the style.css? I perfer creating a block because there are other styling that is specific to this section along with observers that are fired when scrolled after the block placement in the doc

👍

**Review by ravverma — APPROVED** [review]
LGTM

**Comment by JiangLong2019** [comment]
>Yes, I have skipped it intentionally and have opened a question for the customer to recommend the business rules and account creation flow once we click on the submit button. I have added the mobile number validation from their website and the rest can be added once they respond to that.

Great! I think maybe the Sign Up block can reuse the logic @sneharora1

**Pull request merged**
